version: '3'

services:
  server:
    image: gokit-lorem-grpc
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/11.gokit-lorem-grpc
    command: ["go", "run", "server/main.go"]

  client:
    image: gokit-lorem-grpc
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/11.gokit-lorem-grpc
    command: ["go", "run", "client/main.go"]
