version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - ./docker/grafana_db:/var/lib/grafana grafana/grafana
  lorem:
    image: golang:1.12
    ports:
      - 8080:8080
    environment:
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/main.go"]
