version: '3'

services:
  consul-svc:
    image: consul
    ports:
      - 8500:8500
    command: ["agent", "-dev", "-ui", "-client=0.0.0.0"]

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  server1:
    image: gokit-lorem-tracing-02
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/07.gokit链路追踪/02.gokit-lorem-tracing-consul
    environment:
      SERVER_ADDR: server1
      SERVER_PORT: "8080"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
    command: ["go", "run", "server/main.go"]

  server2:
    image: gokit-lorem-tracing-02
    ports:
      - 8081:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/07.gokit链路追踪/02.gokit-lorem-tracing-consul
    environment:
      SERVER_ADDR: server2
      SERVER_PORT: "8080"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
    command: ["go", "run", "server/main.go"]

  client:
    image: gokit-lorem-tracing-02
    ports:
      - 8090:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/07.gokit链路追踪/02.gokit-lorem-tracing-consul
    environment:
      SERVER_ADDR: ## 留空
      SERVER_PORT: "8080"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
    command: ["go", "run", "client/main.go"]
