version: '3'

services:
  consul-svc:
    image: consul
    ports:
      - 8500:8500
    command: ["agent", "-dev", "-ui", "-client=0.0.0.0"]

  server1:
    image: golang:1.12
    ports:
      - 8080:8080
    environment:
      - SERVER_ADDR=server1
      - SERVER_PORT=8080
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/server/main.go"]

  server2:
    image: golang:1.12
    ports:
      - 8081:8080
    environment:
      - SERVER_ADDR=server2
      - SERVER_PORT=8080
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/server/main.go"]

  client:
    image: golang:1.12
    ports:
      - 8090:8080
    environment:
      - SERVER_ADDR= ## 留空
      - SERVER_PORT=8080
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/client/main.go"]
