version: '3'

services:
  server:
    image: gokit-lorem-restful-04
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/04.gokit-lorem-restful-client
    command: ["go", "run", "server/main.go"]

  client:
    image: gokit-lorem-restful-04
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/04.gokit-lorem-restful-client
    command: ["go", "run", "client/main.go"]
