version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  server:
    image: golang:1.12
    ports:
      - 8080:8080
    environment:
      SERVER_ADDR: ## 留空
      SERVER_PORT: "8080"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
      GO111MODULE: auto
      GOPROXY: https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/server/main.go"]

  client:
    image: golang:1.12
    ports:
      - 8090:8080
    environment:
      SERVER_ADDR: ## 留空
      SERVER_PORT: "8080"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
      GO111MODULE: auto
      GOPROXY: https://goproxy.io
    volumes:
      - .:/gokit
    working_dir: /gokit
    command: ["go", "run", "cmd/client/main.go"]
